#!/usr/bin/env perl
#
# Munin plugin for monitoring PHP-FPM memory usage
# Credit to TJ Stein 2010 http://constantshift.com
#
# Magic markers:
#%# family=manual
#%# capabilities=autoconf

my $PHP_BIN = exists $ENV{'phpbin'} ? $ENV{'phpbin'} : "php-fpm";
my $PHP_POOL = exists $ENV{'phppool'} ? $ENV{'phppool'} : "www";

if ( defined $ARGV[0] and $ARGV[0] eq "autoconf" )
{
    print "yes\n";
    exit 0;
}

if ( defined $ARGV[0] and $ARGV[0] eq "config" ) {
    print "graph_title PHP-FPM Memory Usage\n";
    print "graph_vlabel RAM\n";
    print "graph_category PHP\n";
    print "ram.label ram\n";
    print "graph_args --base 1024\n";
	exit 0;
}

my $i = Integer;
@cmd = `ps auwx | grep "$PHP_BIN: pool $PHP_POOL" | grep -v grep | grep -v phpfpm_memory`;
foreach (@cmd) {
    @return = split(/ +/, $_);
    $i += @return[5]*1024;
}
print "ram.value ".$i."\n";
