#!/bin/sh
# -*- sh -*-
#
# Plugin to monitor the number of PHP-FPM processes on the machine.
#
# Copyright TJ Stein 2010 http://constantshift.com
# Modified by Skylar Kelty 2016
#
# Magic markers:
#%# family=manual
#%# capabilities=autoconf

PHP_BIN=${phpbin-"php-fpm"}
PHP_POOL=${phppool-"www"}

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title PHP-FPM Processes'
    echo 'graph_args --base 1000 -l 0 '
    echo 'graph_vlabel PHP-FPM Processes'
    echo 'graph_category PHP'
    echo 'graph_info This graph shows the number of PHP-FPM processes in the system.'
    echo 'php_processes.label PHP-FPM Processes'
    echo 'php_processes.draw LINE2'
    echo 'php_processes.info The current number of PHP-FPM processes.'
    exit 0
fi

echo -n "php_processes.value "
ps awwwux | grep "$PHP_BIN: pool $PHP_POOL" | grep -v grep | wc -l
