#!/usr/bin/env perl
#
# Munin plugin for monitoring PHP-FPM memory usage
#
# Copyright TJ Stein 2010 http://constantshift.com
# Modified by Skylar Kelty 2016
#
# Magic markers:
#%# family=manual
#%# capabilities=autoconf

my $PHP_BIN = exists $ENV{'phpbin'} ? $ENV{'phpbin'} : "php-fpm";
my $PHP_POOL = exists $ENV{'phppool'} ? $ENV{'phppool'} : "www";

if ( defined $ARGV[0] and $ARGV[0] eq "autoconf" )
{
    print "yes\n";
    exit 0;
}

if ( defined $ARGV[0] and $ARGV[0] eq "config" ) {
    print "graph_title PHP-FPM Memory Usage\n";
    print "graph_vlabel RAM\n";
    print "graph_category PHP\n";
    print "ram.label ram\n";
    print "graph_args --base 1024\n";
	exit 0;
}

my %masters = ();
my $i = Integer;

@cmd = `ps axwww -o pid,ppid,vsz,command | grep "$PHP_BIN: master process" | grep -v grep | grep -v phpfpm_memory`;
foreach (@cmd) {
    @return = split(/ +/, $_);
    $masters{@return[0]} = @return[2] * 1024;
}

@cmd = `ps axwww -o pid,ppid,vsz,command | grep "$PHP_BIN: pool $PHP_POOL" | grep -v grep | grep -v phpfpm_memory`;
foreach (@cmd) {
    @return = split(/ +/, $_);

    if ($i == 0) {
	$i += $masters{$return[1]};
    }

    $i += (@return[2] * 1024) - $masters{$return[1]};
}

print "ram.value ".$i."\n";
